djangoShop/basket/urls.py
from django.urls import path

from basket import views


app_name = "basket"

urlpatterns = [
    path(
        "basket_add/",
        views.BasketAddView.as_view(),
        name="basket_add",
    ),
    path(
        "basket_change/",
        views.BasketChangeView.as_view(),
        name="basket_change",
    ),
    path(
        "basket_remove/",
        views.BasketRemoveView.as_view(),
        name="basket_remove",
    ),
]

djangoShop/djangoShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from djangoShop.settings import DEBUG
from djangoShop import settings


urlpatterns = [
    path("", include("main.urls")),
    path("catalog/", include("goods.urls")),
    path("user/", include("users.urls")),
    path("basket/", include("basket.urls")),
    path("orders/", include("orders.urls")),
    path("admin/", admin.site.urls),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoShop/goods/urls.py
from django.urls import path

from goods import views

app_name = "catalog"

urlpatterns = [
    path("search/", views.CatalogView.as_view(), name="search"),
    path("<slug:category_slug>/", views.CatalogView.as_view(), name="catalog"),
    path("product/<slug:product_slug>/", views.ProductView.as_view(), name="product"),
]

djangoShop/main/urls.py
from django.urls import path

from main import views

app_name = "main"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
]

djangoShop/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("registration/", views.RegistrationView.as_view(), name="registration"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("basket/", views.BasketView.as_view(), name="basket"),
    path("logout/", views.logout, name="logout"),
]

djangoShop/basket/models.py
from django.db import models

from goods.models import Product
from users.models import User


class BasketQuerySet(models.QuerySet):

    def total_price(self):
        return sum(basket.products_price() for basket in self)

    def total_quantity(self):
        if self:
            return sum(basket.quantity for basket in self)
        return 0


class Basket(models.Model):

    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        verbose_name="User",
        blank=True,
        null=True,
    )
    product = models.ForeignKey(
        to=Product,
        on_delete=models.CASCADE,
        verbose_name="Product",
    )
    quantity = models.PositiveSmallIntegerField(
        default=0,
        verbose_name="Quantity",
    )
    session_key = models.CharField(
        max_length=32,
        blank=True,
        null=True,
    )
    created_timestamp = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Add time",
    )

    class Meta:
        db_table = "basket"
        verbose_name = "Basket"
        verbose_name_plural = "Baskets"
        ordering = ["id"]

    objects = BasketQuerySet().as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self) -> str:
        if self.user:
            return f"Корзина {self.user.username} | Товар {self.product.name} | Количество {self.quantity}"

        return f"Анонимная корзина | Товар {self.product.name} | Количество {self.quantity}"

djangoShop/orders/models.py
from django.db import models

from goods.models import Product
from users.models import User


class OrderItemQuerySet(models.QuerySet):

    def total_price(self):
        return sum(product.products_price() for product in self)

    def total_quantity(self):
        if self:
            return sum(product.quantity for product in self)
        return 0


class Order(models.Model):
    user = models.ForeignKey(
        to=User,
        verbose_name="Пользователь",
        on_delete=models.SET_DEFAULT,
        default=None,
        blank=True,
        null=True,
    )
    created_timestamp = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создания заказа",
    )
    phone_number = models.CharField(
        max_length=20,
        verbose_name="Номер телефона",
    )
    requires_delivery = models.BooleanField(
        default=False,
        verbose_name="Требуется доставка",
    )
    delivery_address = models.TextField(
        null=True,
        blank=True,
        verbose_name="Адрес доставки",
    )
    payment_on_get = models.BooleanField(
        default=False,
        verbose_name="Оплата при получении",
    )
    is_paid = models.BooleanField(
        default=False,
        verbose_name="Оплачено",
    )
    status = models.CharField(
        max_length=50,
        default="В обработке",
        verbose_name="Статус заказа",
    )

    class Meta:
        db_table: str = "Order"
        verbose_name: str = "Order"
        verbose_name_plural: str = "Orders"
        ordering = ["id"]

    def __str__(self) -> str:
        return f"Order № {self.pk} | Customer {self.user.first_name} {self.user.last_name} "


class OrderItem(models.Model):
    order = models.ForeignKey(
        to=Order,
        verbose_name="Заказ",
        on_delete=models.CASCADE,
    )
    product = models.ForeignKey(
        to=Product,
        verbose_name="Товар",
        on_delete=models.CASCADE,
        default=None,
        null=True,
    )
    name = models.CharField(
        max_length=150,
        verbose_name="Название",
    )
    price = models.DecimalField(
        max_digits=7,
        decimal_places=2,
        verbose_name="Цена",
    )
    quantity = models.PositiveIntegerField(
        default=0,
        verbose_name="Количество",
    )
    created_timestamp = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата продажи",
    )

    class Meta:
        db_table: str = "Order item"
        verbose_name: str = "Sold product"
        verbose_name_plural: str = "Sold products"
        ordering = ["id"]

    objects = OrderItemQuerySet.as_manager()

    def products_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self) -> str:
        return f"Product {self.name} | Order № {self.order.pk}"

djangoShop/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(
        upload_to="users_images",
        blank=True,
        null=True,
        verbose_name="Avatar",
    )
    phone_number = models.CharField(
        max_length=10,
        blank=True,
        null=True,
    )

    class Meta:
        db_table: str = "Users"
        verbose_name: str = "User"
        verbose_name_plural: str = "Users"

    def __str__(self) -> str:
        return self.username

djangoShop/users/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserCreationForm,
    UserChangeForm,
)

from users.models import User


class UserLoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = [
            "username",
            "password",
        ]


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        ]

    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.CharField()


class UserProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = [
            "image",
            "first_name",
            "last_name",
            "username",
            "email",
        ]

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.CharField()

djangoShop/basket/views.py
from django.http import JsonResponse
from django.views import View

from basket.models import Basket
from goods.models import Product
from basket.mixins import BasketMixin


class BasketAddView(BasketMixin, View):

    def post(self, request):
        product_id = request.POST.get("product_id")
        product = Product.objects.get(id=product_id)

        basket = self.get_basket(request, product=product)

        if basket:
            basket.quantity += 1
            basket.save()
        else:
            Basket.objects.create(
                user=request.user if request.user.is_authenticated else None,
                session_key=(
                    request.session.session_key
                    if not request.user.is_authenticated
                    else None
                ),
                product=product,
                quantity=1,
            )

        response_data = {
            "message": "Product added to the basket",
            "cart_items_html": self.render_basket(request),
        }

        return JsonResponse(response_data)


class BasketChangeView(BasketMixin, View):

    def post(self, request):
        basket_id = request.POST.get("cart_id")
        quantity = request.POST.get("quantity")
        basket = self.get_basket(request, basket_id=basket_id)

        basket.quantity = quantity
        basket.save()

        response_data = {
            "message": "Quantity changed",
            "cart_items_html": self.render_basket(request),
            "quantity": quantity,
        }

        return JsonResponse(response_data)


class BasketRemoveView(BasketMixin, View):

    def post(self, request):
        basket_id = request.POST.get("cart_id")
        basket = self.get_basket(request, basket_id=basket_id)
        quantity = basket.quantity

        basket.delete()

        response_data = {
            "message": "Product deleted",
            "cart_items_html": self.render_basket(request),
            "quantity_deleted": quantity,
        }

        return JsonResponse(response_data)

djangoShop/users/views.py
import json
from typing import TYPE_CHECKING

from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.base import Model as Model
from django.forms import BaseModelForm
from django.views.generic import (
    CreateView,
    UpdateView,
    TemplateView,
)
from django.http import (
    HttpResponse,
    HttpResponseRedirect,
)
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.contrib import auth, messages
from django.db.models import Prefetch

from rabbitmq.producer import produce

from basket.models import Basket
from common.mixins import CacheMixin
from orders.models import Order, OrderItem
from users.forms import (
    UserLoginForm,
    UserProfileForm,
    UserRegistrationForm,
)

if TYPE_CHECKING:
    from django.http import HttpResponse, HttpRequest


class LoginView(LoginView):
    template_name = "users/login.html"
    form_class = UserLoginForm
    success_url = reverse_lazy("main:home")

    def get_success_url(self):
        redirect_page = self.request.POST.get("next", None)
        if redirect_page and redirect_page != reverse_lazy("users:logout"):
            return redirect_page
        return reverse_lazy("main:home")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "BYD - Authentication"
        return context

    def form_valid(self, form):
        session_key = self.request.session.session_key

        user = form.get_user()

        if user:
            auth.login(self.request, user)

            if session_key:
                old_baskets = Basket.objects.filter(user=user)

                if old_baskets.exists():
                    old_baskets.delete()

                Basket.objects.filter(session_key=session_key).update(user=user)

                messages.success(
                    self.request,
                    f"{user.username}, you signed in",
                )

                return HttpResponseRedirect(self.get_success_url())

        return super().form_valid(form)


class RegistrationView(CreateView):
    template_name = "users/registration.html"
    form_class = UserRegistrationForm
    success_url = reverse_lazy("users:profile")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "BYD - Registration"
        return context

    def form_valid(self, form):
        session_key = self.request.session.session_key

        user = form.instance

        if user:
            form.save()
            auth.login(self.request, user)

            user_data = {
                "email": user.email,
                "password": user.password,
            }

            produce(json.dumps(user_data))

        if session_key:
            Basket.objects.filter(session_key=session_key).update(user=user)

        messages.success(
            self.request,
            f"{user.username}, registration successfully completed and you signed in",
        )

        return HttpResponseRedirect(self.success_url)


class ProfileView(LoginRequiredMixin, CacheMixin, UpdateView):
    template_name = "users/profile.html"
    form_class = UserProfileForm
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request, "Your profile successfully updated")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Something went wrong")
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "BYD - Profile"

        orders = (
            Order.objects.filter(user=self.request.user)
            .prefetch_related(
                Prefetch(
                    "orderitem_set",
                    queryset=OrderItem.objects.select_related("product"),
                )
            )
            .order_by("-id")
        )
        context["orders"] = self.set_get_cache(
            orders,
            f"user_orders_{self.request.user.id}",
            60,
        )

        return context


class BasketView(TemplateView):
    template_name = "users/basket.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "BYD - Basket"
        return context


@login_required
def logout(request: "HttpRequest") -> "HttpResponse":
    messages.warning(
        request,
        "You logged out!",
    )
    auth.logout(request)
    return redirect(reverse("main:home"))

djangoShop/templates/users/login.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                <h2 class="text-center mb-4">Authorization</h2>
                <form action="{% url "users:login" %}" method="post">
                    {% csrf_token %}
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value={{ request.GET.next }}>
                    {% endif %}
                    <div class="mb-3">
                        <label for="id_username" class="form-label">Username</label>
                        <input type="text" class="form-control" name="username" id="id_username" value="{% if form.username.value %}{{ form.username.value }}{% endif %}" placeholder="Enter your username" required>
                    </div>
                    <div class="mb-3">
                        <label for="id_password" class="form-label">Password</label>
                        <input type="password" class="form-control" name="password" id="id_password" placeholder="Enter your password" required>
                    </div>
                    <button type="submit" class="btn btn-dark btn-block">Enter</button>
                </form>
                <div class="mt-3">
                    <a href="#">Forgot password?</a> | <a href="{% url "users:registration" %}">Registration</a>
                </div>
                <hr>
                <div class="text-center">
                    <p>Login via:</p>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/google.svg" %}" alt="Catalog Icon" width="16" height="16">
                        Google
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/facebook.svg" %}" alt="Catalog Icon" width="16" height="16">
                        Facebook
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/github.svg" %}" alt="Catalog Icon" width="16" height="16">
                        GitHub
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

djangoShop/templates/users/profile.html
{% extends "main/base.html" %}
{% load static %}
{% load baskets_tags %}


{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row">
            <!-- Профиль с данными пользователя -->
            <div class="col-md-5">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">User profile</h3>
                    <form action="{% url "users:profile" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12 mb-3 text-center">
                                {% if user.image %}
                                    <img src="{{ user.image.url }}"
                                        alt="User avatar" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                {% else %}
                                    <img src="{% static "deps/images/baseavatar.jpg" %}"
                                        alt="User avatar" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                {% endif %}
                                <input type="file" class="form-control mt-3" id="id_image"
                                    name="image"
                                    accept="image/*">
                                    {% if form.image.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.image.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_first_name" class="form-label">Name*</label>
                                <input type="text" class="form-control" id="id_first_name"
                                    name="first_name"
                                    placeholder="Enter your name"
                                    value="{{ form.first_name.value }}" required>
                                    {% if form.first_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_last_name" class="form-label">Lastname*</label>
                                <input type="text" class="form-control" id="id_last_name"
                                    name="last_name"
                                    placeholder="Enter your lastname"
                                    value="{{ form.last_name.value }}" required>
                                    {% if form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_username" class="form-label">Username*</label>
                                <input type="text" class="form-control" id="id_username"
                                    name="username"
                                    placeholder="Enter your имя пользователя"
                                    value="{{ form.username.value }}" required>
                                    {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                    name="email"
                                    placeholder="Enter your email *youremail@example.com"
                                    value="{{ form.email.value }}" required>
                                    {% if form.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                    {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Save</button>
                    </form>
                </div>
            </div>
            <!-- Корзина -->
            {% user_baskets request as baskets %}
            <div class="col-md-7">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Basket</h3>
                    <div class="container" id="cart-items-container">
                        <!-- Разметка корзины -->
                        {% include "includes/included_basket.html" %}
                        <!-- Закончилась разметка корзины -->
                    </div>
                </div>
            </div>
            <!-- Оформленные заказы -->
            <div class="col-md-12">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">My orders</h3>
                    <!-- Разметка заказов -->
                    <div class="container">
                        <div class="accordion" id="accordionExample">
                            {% for order in orders %}
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading{{ order.id }}">
                                    <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}" aria-expanded="false" aria-controls="collapse{{ order.id }}">
                                        Order № {{ order.id }} - {{ order.created_timestamp }} | Status:<strong class="mx-2">{{ order.status }}</strong>
                                    </button>
                                </h2>
                                <div id="collapse{{ order.id }}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading2" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Товар</th>
                                                    <th>Количество</th>
                                                    <th>Цена</th>
                                                    <th>Общая стоимость</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for item in order.orderitem_set.all %}
                                                <tr>
                                                    <td><a class="text-white" href="{% url "catalog:product" item.product.slug %}">{{ item.product.name }}</a></td>
                                                    <td>{{ item.quantity }}</td>
                                                    <td>{{ item.price }} $</td>
                                                    <td>{{ item.products_price }} $</td>
                                                    
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <!-- Закончилась разметка заказов -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

djangoShop/templates/users/registration.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Registration</h2>
                <form action="{% url "users:registration" %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Name*</label>
                            <input type="text" class="form-control" id="id_first_name"
                                value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                name="first_name"
                                placeholder="Enter your firstname" required>
                                {% if form.first_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Lastname*</label>
                            <input type="text" class="form-control" id="id_last_name"
                                value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                name="last_name"
                                placeholder="Enter your lastname" required>
                                {% if form.last_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_username" class="form-label">Username*</label>
                            <input type="text" class="form-control" id="id_username"
                                value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                name="username"
                                placeholder="Enter your username" required>
                                {% if form.username.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Email*</label>
                            <input type="email" class="form-control" id="id_email"
                                value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                name="email"
                                placeholder="Enter your email" required>
                                {% if form.email.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password1" class="form-label">Password*</label>
                            <input type="password" class="form-control" id="id_password1"
                                value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                                name="password1"
                                placeholder="Enter your password" required>
                                {% if form.password1.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password2" class="form-label">Confirm the password*</label>
                            <input type="password" class="form-control" id="id_password2"
                                value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                                name="password2"    
                                placeholder="Confirm the password" required>
                                {% if form.password2.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                                {% endif %}
                        </div>
                    </div>
                    <button type="submit"
                        class="btn btn-dark btn-block">Register</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}