djangoShop/djangoShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from djangoShop.settings import DEBUG
from djangoShop import settings


urlpatterns = [
    path("", include("main.urls")),
    path("catalog/", include("goods.urls")),
    path("user/", include("users.urls")),
    path("basket/", include("basket.urls")),
    path("orders/", include("orders.urls")),
    path("admin/", admin.site.urls),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoShop/main/urls.py
from django.urls import path

from main import views

app_name = "main"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
]

djangoShop/orders/urls.py
from django.urls import path

from . import views

app_name = "orders"

urlpatterns = [
    path("create-order/", views.CreateOrderView.as_view(), name="create_order"),
]

djangoShop/orders/models.py
from django.db import models

from goods.models import Product
from users.models import User


class OrderItemQuerySet(models.QuerySet):

    def total_price(self):
        return sum(product.products_price() for product in self)

    def total_quantity(self):
        if self:
            return sum(product.quantity for product in self)
        return 0


class Order(models.Model):
    user = models.ForeignKey(
        to=User,
        verbose_name="Пользователь",
        on_delete=models.SET_DEFAULT,
        default=None,
        blank=True,
        null=True,
    )
    created_timestamp = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создания заказа",
    )
    phone_number = models.CharField(
        max_length=20,
        verbose_name="Номер телефона",
    )
    requires_delivery = models.BooleanField(
        default=False,
        verbose_name="Требуется доставка",
    )
    delivery_address = models.TextField(
        null=True,
        blank=True,
        verbose_name="Адрес доставки",
    )
    payment_on_get = models.BooleanField(
        default=False,
        verbose_name="Оплата при получении",
    )
    is_paid = models.BooleanField(
        default=False,
        verbose_name="Оплачено",
    )
    status = models.CharField(
        max_length=50,
        default="В обработке",
        verbose_name="Статус заказа",
    )

    class Meta:
        db_table: str = "Order"
        verbose_name: str = "Order"
        verbose_name_plural: str = "Orders"
        ordering = ["id"]

    def __str__(self) -> str:
        return f"Order № {self.pk} | Customer {self.user.first_name} {self.user.last_name} "


class OrderItem(models.Model):
    order = models.ForeignKey(
        to=Order,
        verbose_name="Заказ",
        on_delete=models.CASCADE,
    )
    product = models.ForeignKey(
        to=Product,
        verbose_name="Товар",
        on_delete=models.CASCADE,
        default=None,
        null=True,
    )
    name = models.CharField(
        max_length=150,
        verbose_name="Название",
    )
    price = models.DecimalField(
        max_digits=7,
        decimal_places=2,
        verbose_name="Цена",
    )
    quantity = models.PositiveIntegerField(
        default=0,
        verbose_name="Количество",
    )
    created_timestamp = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата продажи",
    )

    class Meta:
        db_table: str = "Order item"
        verbose_name: str = "Sold product"
        verbose_name_plural: str = "Sold products"
        ordering = ["id"]

    objects = OrderItemQuerySet.as_manager()

    def products_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self) -> str:
        return f"Product {self.name} | Order № {self.order.pk}"

djangoShop/orders/forms.py
import re
from django import forms


class CreateOrderForm(forms.Form):

    choices = [
        ("0", "False"),
        ("1", "True"),
    ]

    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    requires_delivery = forms.ChoiceField(choices=choices)
    delivery_address = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(choices=choices)

    def clean_phone_number(self):
        data = self.cleaned_data["phone_number"]

        if not data.isdigit():
            raise forms.ValidationError("Phone number should have only numbers")

        pattern = re.compile(r"^\d{10}$")
        if not pattern.match(data):
            raise forms.ValidationError("Phone number wrong format")

        return data

djangoShop/orders/views.py
from typing import TYPE_CHECKING

from django.forms import ValidationError
from django.shortcuts import redirect
from django.db import transaction
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import FormView

from orders.forms import CreateOrderForm
from orders.models import Order, OrderItem
from basket.models import Basket

if TYPE_CHECKING:
    pass


class CreateOrderView(LoginRequiredMixin, FormView):
    template_name = "orders/create_order.html"
    form_class = CreateOrderForm
    success_url = reverse_lazy("users:profile")

    def get_initial(self):
        initial = super().get_initial()
        initial["first_name"] = self.request.user.first_name
        initial["last_name"] = self.request.user.last_name
        return initial

    def form_valid(self, form):
        try:
            with transaction.atomic():
                user = self.request.user
                basket_items = Basket.objects.filter(user=user)

                if basket_items.exists():
                    order = Order.objects.create(
                        user=user,
                        phone_number=form.cleaned_data["phone_number"],
                        requires_delivery=form.cleaned_data["requires_delivery"],
                        delivery_address=form.cleaned_data["delivery_address"],
                        payment_on_get=form.cleaned_data["payment_on_get"],
                    )

                    for basket_item in basket_items:
                        product = basket_item.product
                        name = basket_item.product.name
                        price = basket_item.product.sell_price()
                        quantity = basket_item.quantity

                        if product.quantity < quantity:
                            raise ValidationError(
                                f"Insufficient quantity of goods {name} in the warehouse\
                                                    In stock - {product.quantity}"
                            )

                        OrderItem.objects.create(
                            order=order,
                            product=product,
                            name=name,
                            price=price,
                            quantity=quantity,
                        )
                        product.quantity -= quantity
                        product.save()

                    basket_items.delete()

                    messages.success(self.request, "The order has been placed")
                    return redirect("users:profile")

        except ValidationError as e:
            messages.success(self.request, str(e))
            return redirect("orders:create_order")

    def form_invalid(self, form):
        messages.error(self.request, "The order was not placed")
        return redirect("orders:create_order")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "BYD - Making an order"
        context["order"] = True
        return context

djangoShop/templates/orders/create_order.html
{% extends "main/base.html" %}
{% load static %}
{% load baskets_tags %}


{% block content %}
<div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
    <div class="container">
        <h3 class="text-center mb-4">Selected products</h3>
        <div class="container" id="cart-items-container">
            <!-- Разметка корзины -->
            {% user_baskets request as baskets %}
            <div class="col-md-7">
                <h3 class="text-center mb-4">Basket</h3>
                <div class="container" id="cart-items-container">
                    <!-- Разметка корзины -->
                    {% include "includes/included_basket.html" %}
                    <!-- Закончилась разметка корзины -->
                </div>
            </div>
            <!-- Закончилась разметка корзины -->
        </div>
    </div>
    <!-- Детали заказа -->
    <div class="container">
        <h3 class="text-center">Order details</h3>
        <div class="card mb-3">
            <div class="card-body">
                <form action="{% url "orders:create_order" %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Firstname*:</label>
                            <input type="text" class="form-control" id="id_first_name"
                                value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                {% if form.first_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                {% endif %}
                                name="first_name" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Lastname*:</label>
                            <input type="text" class="form-control" id="id_last_name"
                                value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                {% if form.last_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                {% endif %}
                                name="last_name" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_phone_number" class="form-label">Phone number*:</label>
                            <input type="text" class="form-control" id="id_phone_number" name="phone_number"
                            value="{% if form.phone_number.value %}{{ form.phone_number.value }}{% endif %}"
                                placeholder="В формате: XXX-XXX-XX-XX"
                                required>
                                {% if form.phone_number.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.phone_number.errors }}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="delivery" class="form-label">Delivery: </label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="requires_delivery"
                                    id="id_requires_delivery" value="1" checked>
                                <label class="form-check-label" for="id_requires_delivery">Need delivery</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="requires_delivery"
                                    id="id_requires_delivery" value="0">
                                <label class="form-check-label" for="id_requires_delivery">Pickup</label>
                            </div>
                        </div>
                        <div class="mb-3" id="deliveryAddressField">
                            <label for="id_delivery_address" class="form-label">Delivery address*:</label>
                            <textarea class="form-control" id="id_delivery_address"
                                value="{% if form.delivery_address.value %}{{ form.delivery_address.value }}{% endif %}"
                                {% if form.delivery_address.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.delivery_address.errors }}</div>
                                {% endif %}
                                name="delivery_address" rows="2"></textarea>
                        </div>
                        <div class="col-md-12 mb-3">
                            <label class="form-label">Payment method: </label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="payment_on_get"
                                    id="id_payment_on_get" value="0" checked>
                                <label class="form-check-label" for="id_payment_on_get">Payment
                                    by card</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="payment_on_get"
                                    id="id_payment_on_get" value="1">
                                <label class="form-check-label" for="id_payment_on_get">In cash/by card
                                    upon receipt</label>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-dark">Place an order</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}