djangoShop/basket/urls.py
from django.urls import path

from basket import views


app_name = "basket"

urlpatterns = [
    path(
        "basket_add/",
        views.BasketAddView.as_view(),
        name="basket_add",
    ),
    path(
        "basket_change/",
        views.BasketChangeView.as_view(),
        name="basket_change",
    ),
    path(
        "basket_remove/",
        views.BasketRemoveView.as_view(),
        name="basket_remove",
    ),
]

djangoShop/djangoShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from djangoShop.settings import DEBUG
from djangoShop import settings


urlpatterns = [
    path("", include("main.urls")),
    path("catalog/", include("goods.urls")),
    path("user/", include("users.urls")),
    path("basket/", include("basket.urls")),
    path("orders/", include("orders.urls")),
    path("admin/", admin.site.urls),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoShop/main/urls.py
from django.urls import path

from main import views

app_name = "main"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
]

djangoShop/orders/urls.py
from django.urls import path

from . import views

app_name = "orders"

urlpatterns = [
    path("create-order/", views.CreateOrderView.as_view(), name="create_order"),
]

djangoShop/templates/includes/basket_button.html
{% load static %}
{% load baskets_tags %}

{% user_baskets request as baskets %}


<div>
    <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
        aria-expanded="false">
        <img class="mx-1" src="{% static "deps/icons/basket2-fill.svg" %}" alt="Catalog Icon" width="24"
            height="24">
        <span id="goods-in-cart-count">{{ baskets.total_quantity }}</span>
    </button>
</div>
<!-- Разметка модального окна корзины -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                    aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h3 class="text-center mb-4">Basket</h3>
                <div class="container" id="cart-items-container">
                    <!-- Разметка корзины -->
                    {% include "includes/included_basket.html" %}
                    <!-- Закончилась разметка корзины -->
                </div>
            </div>
        </div>
    </div>
</div>

djangoShop/templates/includes/included_basket.html
{% load static %}


<div class="card mb-3 text-bg-light shadow-lg">
    {% for basket in baskets %}
        <div class="card-header">
            <h5 class="card-title">{{ basket.product.name }}</h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <div class="row text-center">
                    <div class="col p-0">
                        <div class="input-group">
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-dark btn-sm decrement"
                                    data-cart-id="{{ basket.id }}" 
                                    data-cart-change-url="{% url "basket:basket_change" %}">
                                    {% csrf_token %}
                                    -</button>
                            </span>
                            <input type="text" class="form-control number" value="{{ basket.quantity }}"
                                readonly>
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-dark btn-sm increment"
                                    data-cart-id="{{ basket.id }}" 
                                    data-cart-change-url="{% url "basket:basket_change" %}">
                                    {% csrf_token %}
                                    +</button>
                            </span>
                        </div>
                    </div>
                    <div class="col p-0">
                        <p>x {{ basket.product.sell_price }} = </p>
                    </div>
                    <div class="col p-0"><strong>{{ basket.products_price }} $</strong></div>
                    <div class="col p-0">
                        <a href="{% url "basket:basket_remove" %}" class="remove-from-cart"
                        data-cart-id="{{ basket.id }}">
                            {% csrf_token %}
                            <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}"
                                alt="Catalog Icon" width="16" height="16">
                        </a>
                    </div>
                </div>
            </li>
        </ul>
    {% endfor %}
</div>
<div class="card mb-3 shadow-lg">
    <div class="card-footer">
        <p class="float-left">Total <strong>{{ baskets.total_quantity }}</strong> product(s) amount of</p>
        <h4 class="float-left"><strong>{{ baskets.total_price }} $</strong></h4>
    </div>
</div>
{% if baskets and not order %}
<a class="btn btn-dark" href="{% url "orders:create_order" %}">
    Place an order
</a>
{% endif %}

djangoShop/templates/includes/notifications.html
{% load static %}


{% if form.non_field_errors %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">
                {{ form.non_field_errors }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </div>
    </div>
</div>
{% endif %}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                    {% if message.tags == 'warning' %}
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-danger fade show custom-shadow" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                {% endfor %}
            {% else %}
            <div id="jq-notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" style="display: none;" role="alert">
            </div>
            {% endif %}
        </div>
    </div>
</div>