djangoShop/djangoShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from djangoShop.settings import DEBUG
from djangoShop import settings


urlpatterns = [
    path("", include("main.urls")),
    path("catalog/", include("goods.urls")),
    path("user/", include("users.urls")),
    path("basket/", include("basket.urls")),
    path("orders/", include("orders.urls")),
    path("admin/", admin.site.urls),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoShop/goods/urls.py
from django.urls import path

from goods import views

app_name = "catalog"

urlpatterns = [
    path("search/", views.CatalogView.as_view(), name="search"),
    path("<slug:category_slug>/", views.CatalogView.as_view(), name="catalog"),
    path("product/<slug:product_slug>/", views.ProductView.as_view(), name="product"),
]

djangoShop/main/urls.py
from django.urls import path

from main import views

app_name = "main"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
]

djangoShop/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("registration/", views.RegistrationView.as_view(), name="registration"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("basket/", views.BasketView.as_view(), name="basket"),
    path("logout/", views.logout, name="logout"),
]

djangoShop/main/models.py
# Create your models here.

djangoShop/main/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "main/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "BYD - Home Page"
        context["content"] = "BYD PC Store"
        return context


class AboutView(TemplateView):
    template_name = "main/about.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "BYD - About us"
        context["content"] = "About us"
        context["text_on_page"] = "Some text about our company"
        return context

djangoShop/templates/main/about.html
{% extends "main/base.html" %}
{% load static %}



{% block modal_basket %}
    {% include "includes/basket_button.html" %}
{% endblock modal_basket %}


{% block footer_style %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock footer_style %}


{% block content %}
<div class="mt-5 pt-5 bg-white custom-shadow rounded">
    <h2 class="m-2"><strong>{{ content }}</strong></h2>
    <p class="m-2">{{ text_on_page }}</p>
</div>
{% endblock content %}


{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Build Your Dream</p>
    </div>
</footer>
{% endblock footer %}

djangoShop/templates/main/base.html
{% load static %}
{% load goods_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    <!-- Стиль footer-a для главной страницы -->
    {% block footer_style %}{% endblock footer_style %}
    <!-- Favicons for different platforms -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">
    <title>{{ title }}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url "main:home" %}">BYD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Info
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="#">Delivery and payment</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Contact information</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url "main:about" %}">About us</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="{% url "users:basket" %}">Basket</a>
                        </li>
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link  text-white" href="{% url "users:login" %}">Sign In</a>
                            </li>
                        {% else %}
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                My profile
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="{% url "users:basket" %}">Basket</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url "users:profile" %}">My profile</a>
                                </li>
                                {% if user.is_admin or user.is_staff %}
                                    <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Admin panel</a></li>
                                {% endif %}
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                    <a class="dropdown-item  text-white" href="{% url "users:logout" %}">Sign Out</a>
                                </li>
                            </ul>
                        </li>
                        {% endif %}
                    </ul>
                    <form class="d-flex" role="search" action="{% url "catalog:search" %}" method="get">
                        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- Каталог и корзина с фиксированным расположением на странице -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Каталог -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Catalog
                        <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16"
                            height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        {% goods_categories as categories%}
                        {% for category in categories %}
                            <li><a class="dropdown-item text-white" href="{% url "catalog:catalog" category.slug %}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- Значек корзины, вызывает модальное окно -->
                {% block modal_basket %}{% endblock modal_basket %}
                <!-- Закончилась разметка модального окна -->
            </div>
        </div>
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на Ваше усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    {% include "includes/notifications.html" %}
                    {% block content %}{% endblock content %}
                </div>
            </div>
        </div>
    </section>
    {% block footer %}{% endblock footer %}
    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
</body>

</html>

djangoShop/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}


{% block modal_basket %}
    {% include "includes/basket_button.html" %}
{% endblock modal_basket %}


{% block footer_style %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock footer_style %}


{% block content %}
    <h1 class="mt-5 pt-5"><strong>{{ content }}</strong></h1>
{% endblock content %}


{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Build Your Dream</p>
    </div>
</footer>
{% endblock footer %}